export const restaurant = {
  name:     'Pizzeria Ristorante Acqua Blu',
  short:    'Acqua Blu',
  tagline:  'Ægte siciliansk køkken — midt i Blåvand',
  story:    'Restauranten drives af to sicilianske brødre, Salvatore og Rino Lalicata. Acqua Blu er en af de få ægte italienske restauranter på Vestkysten — hvilket vi er stolte af. Alle vores retter bliver tilberedt helt fra bunden. Vi håber, at jeres besøg vil være en god oplevelse.',
  owners:   'Salvatore og Rino Lalicata',
  address:  'Blåvandvej 28L, 6857 Blåvand',
  phone:    '75 27 98 98',
  email:    'acquablu@acquablu.dk',
  facebook: 'https://www.facebook.com/pages/Acqua-Blu/141785162543501',
  hours:    'Mandag til Søndag · 11:30–21:00',
}

export const pizzas = [
  { nr: 17, name: 'Pizza Margherita',       desc: 'Tomat og ost',                                                          price: '75' },
  { nr: 18, name: 'Pizza Prosciutto e Funghi', desc: 'Tomat, ost, skinke og champignon',                                   price: '89' },
  { nr: 19, name: 'Pizza Pepperoni',         desc: 'Tomat, ost og pepperoni-salami',                                       price: '89' },
  { nr: 20, name: 'Pizza Bolognese',         desc: 'Tomat, ost, løg og oksekødssauce',                                    price: '89' },
  { nr: 21, name: 'Pizza Calzone',           desc: '(Indbagt) Tomat, ost, skinke og champignon',                          price: '92' },
  { nr: 22, name: 'Pizza al Tonno',          desc: 'Tomat, ost, tunfisk og løg',                                           price: '92' },
  { nr: 23, name: 'Pizza Vegetale',          desc: 'Tomat, ost og diverse grønsager',                                     price: '92' },
  { nr: 24, name: 'Pizza Siciliana',         desc: 'Tomat, ost, artiskok, oliven, kapers og løg',                         price: '92' },
  { nr: 25, name: 'Pizza Preferita',         desc: 'Tomat, ost, skinke, champignon, minipølser og asparges',              price: '92' },
  { nr: 26, name: 'Surfers Dream',           desc: 'Tomat, ost, skinke, minipølser, bacon og salami',                     price: '99' },
  { nr: 27, name: 'Pizza e Spaghetti',       desc: 'Ost, spaghetti, skinke og kødsauce',                                  price: '99' },
  { nr: 28, name: 'Pizza Capricciosa',       desc: 'Tomat, ost, oksekød, løg og champignon',                              price: '99' },
  { nr: 29, name: 'Pizza al Salmone',        desc: 'Tomat, ost, røget laks og asparges',                                  price: '99' },
  { nr: 30, name: 'Pizza Quattro Stagioni',  desc: 'Tomat, ost, skinke, oksekød, rejer og peberfrugt',                   price: '99' },
  { nr: 31, name: 'Pizza al Gorgonzola',     desc: 'Tomat, ost, gorgonzola, bacon og oksekød',                            price: '99' },
  { nr: 32, name: 'Pizza Hawaii',            desc: 'Tomat, ost, ananas, rejer og skinke',                                 price: '99' },
  { nr: 33, name: 'Pizza Marinara',          desc: 'Tomat, ost og alt godt fra havet',                                   price: '99' },
  { nr: 34, name: 'Rinos Pizza',             desc: 'Tomat, ost, champignon, oksekød, bacon og spejlæg',                  price: '105' },
  { nr: 35, name: 'Pizza Acqua Blu',         desc: 'Tomat, ost, skinke, champignon, artiskok, salami og oliven',          price: '105' },
  { nr: 36, name: 'Pizza Diavola',           desc: 'Tomat, ost, italiensk stærk salami, paprika og løg',                 price: '99' },
  { nr: 37, name: 'Pizza Parmigiana',        desc: 'Tomat, mozzarella, parmaskinke, parmesan og rucolasalat',             price: '105' },
  { nr: 38, name: 'Pizza Salame',            desc: 'Tomat, ost og italiensk salami',                                     price: '89' },
  { nr: 39, name: 'Pizza Prosciutto',        desc: 'Tomat, ost og skinke',                                               price: '89' },
  { nr: 40, name: 'Pizza Laura',             desc: 'Tomat, ost, ananas og skinke',                                       price: '89' },
  { nr: 41, name: 'Pizza 4 Formaggi',        desc: 'Tomat og 4 forskellige slags ost',                                   price: '96' },
  { nr: 42, name: 'Pizza Victoria',          desc: 'Tomat, ost, skinke, champignon, oksekød og minipølser',              price: '96' },
  { nr: 43, name: 'Pizza Dinamite',          desc: 'Tomat, mozzarella, stærk salami, oliven og jalapeños',               price: '96' },
  { nr: 44, name: 'Pizza Rustica',           desc: 'Tomat, ost, gorgonzola, champignon og løg',                          price: '96' },
  { nr: 45, name: 'Pizza Salvo',             desc: 'Tomat, ost, kylling, artiskok, bacon og løg',                        price: '96' },
  { nr: 46, name: 'Pizza Italia',            desc: 'Tomat, mozzarella, ost, salami, rucolasalat',                        price: '96' },
  { nr: 47, name: 'Pizza Messicana',         desc: 'Tomat, ost, bacon, oksekød, ærter og jalapeños',                     price: '96' },
  { nr: 48, name: 'Pata Pizza',             desc: 'Tomat, ost og pommes frites',                                         price: '82' },
  { nr: 49, name: 'Pizza Fai da te',         desc: 'Sammensæt selv din pizza (tomat + ost + max. 4 ingredienser)',        price: '109' },
]

export const koed = [
  { nr: 55, name: 'Pollo alla griglia',       desc: 'Grillet kylling',                                                    price: '149' },
  { nr: 56, name: 'Costolette di agnello',    desc: 'Grillede lammekoteletter',                                           price: '189' },
  { nr: 57, name: 'Grigliata Mista',          desc: 'Forskellige slags grillet kød',                                     price: '95' },
  { nr: 58, name: 'Bistecca alla griglia',    desc: 'Grillet oksefilet ca. 300g',                                         price: '195' },
  { nr: 59, name: 'Filetto alla griglia',     desc: 'Grillet oksemørbrad',                                               price: '218' },
  { nr: 60, name: 'Saltimbocca alla Romana',  desc: 'Tynd skive oksefilet med parmaskinke og salvie, dampet i hvidvin',  price: '179' },
  { nr: 61, name: 'Bistecca dello Chef',      desc: 'Oksefilet med peberfrugt, champignons, bacon og løg',               price: '189' },
  { nr: 62, name: 'Bistecca ai funghi',       desc: 'Oksefilet med skovsvampe i flødesauce',                             price: '189' },
  { nr: 63, name: 'Bistecca al Gorgonzola',   desc: 'Oksefilet med gorgonzolasauce',                                     price: '189' },
  { nr: 64, name: 'Filetto al Tartufo',       desc: 'Oksemørbrad med trøffel i flødesauce',                              price: '218' },
  { nr: 65, name: 'Filetto al Pepe verde',    desc: 'Flamberet oksemørbrad med cognac og grønne peberkorn i flødesauce', price: '218' },
]
